### ISSUE TITLE
I am always asking for root access 

### ISSUE THREAD

**Issue by vvatermelon-dev** [Lucksi/Darkus#1]
Issue: No superuser binary detected.
Are you rooted? 

does anyone how to fix this???

**Comment by Lucksi** [comment]
Hello Have you tried execute the program with sudo python3 Main.py?

**Comment by vvatermelon-dev** [comment]
> Hello Have you tried execute the program with sudo python3 Main.py?

yes

**Comment by vvatermelon-dev** [comment]
> Hello Have you tried execute the program with sudo python3 Main.py?

![Screenshot_2024-02-10-08-10-17-17_84d3000e3f4017145260f7618db1d683.jpg](https://github.com/Lucksi/Darkus/assets/157937167/2fc98d3e-4195-45e1-9d7a-5ec42743ed86)

**Comment by vvatermelon-dev** [comment]
is this also working in termux??

**Comment by Lucksi** [comment]
No unfortunately this command is only for Linux
